version: '3.3'
services:

  jconon:
    image: consiglionazionalericerche/cool-jconon-lincei:latest
    read_only: false
    ports:
      - 8080:8080
    environment:
    - LANG=it_IT.UTF-8
    - LANGUAGE=it_IT:it
    - LC_ALL=it_IT.UTF-8
    - ORG_APACHE_CHEMISTRY_OPENCMIS_BINDING_CONNECTTIMEOUT=120000
    - REPOSITORY_BASE_URL=http://my-alfresco:8080/alfresco/
    volumes:
    - ./jconon_logs:/logs
    - /tmp
    command: java -Xmx512m -Xss512k -Dspring.profiles.active=lincei -Djava.security.egd=file:/dev/./urandom -jar /opt/selezioni-lincei.war
    labels:
    - SERVICE_NAME=cool-jconon
    external_links:
      - docker-compose_alfresco_1:my-alfresco
